apiVersion: v1
kind: Service
metadata:
  name: jaeger-allinone
  labels:
    app: jaeger
spec:
  ports:
  - port: 6831 
    protocol: UDP
    targetPort: 6831
    nodePort: 30831
  selector:
    app: jaeger
  type: NodePort