apiVersion: v2
appVersion: "2.8.0"
description: Apache Pulsar Helm chart for Kubernetes
name: pulsar
maintainers:
  - name: zzzming
  - name: cdbartholomew
  - name: lhotari
  - name: michaeljmarshall
version: 3.0.4
dependencies:
- name: kube-prometheus-stack
  version: 43.x.x
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: cert-manager
  version: v1.x.x
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: keycloak
  version: 9.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: keycloak.enabled
