image:
  broker:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  brokerSts:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  function:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  zookeeper:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  bookkeeper:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  proxy:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10
  bastion:
    repository: datastax/lunastreaming
    pullPolicy: IfNotPresent
    tag: 2.10_2.10

fullnameOverride: mypulsarcluster
enableAntiAffinity: true
enableTls: false
enableTokenAuth: false
restartOnConfigMapChange:
  enabled: true
extra:
  broker: true
  function: true
  burnell: true
  burnellLogCollector: true
  pulsarHeartbeat: true
  pulsarAdminConsole: true

# 
# - https://github.com/helm/helm/issues/5156
default_storage:
  # existingStorageClassName: 
  reclaimPolicy: Delete

zookeeper:
  replicaCount: 3
  resources:
    requests:
      memory: 300Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms300m -Xmx300m -Djute.maxbuffer=10485760 -XX:+ExitOnOutOfMemoryError"
  volumes:
    data:
      name: data
      size: 2Gi
      # storageClass:
      #   provisioner: rancher.io/local-path
      #   reclaimPolicy: Retain

bookkeeper:
  replicaCount: 3
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  volumes:
    journal:
      name: journal
      size: 2Gi
    ledgers:
      name: ledgers
      size: 5Gi
  configData:
    BOOKIE_MEM: "-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"

broker:
  component: broker
  service:
    annotations: {}
    type: ClusterIP
    headless: false
    ports:
    - name: http
      port: 8080
    - name: pulsar
      port: 6650
  replicaCount: 3
  ledger:
    defaultEnsembleSize: 1
    defaultAckQuorum: 1
    defaultWriteQuorum: 1
  resources:
    requests:
      memory: 600Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms400m -Xmx400m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"
    PULSAR_PREFIX_brokerDeleteInactiveTopicsEnabled: "false"

autoRecovery:
  resources:
    requests:
      memory: 300Mi
      cpu: 0.3

function:
  replicaCount: 1
  functionReplicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  volumes:
    data:
      name: logs
      size: 1Gi
  configData:
    PULSAR_MEM: "-Xms312m -Xmx312m -XX:MaxDirectMemorySize=200m -XX:+ExitOnOutOfMemoryError"

proxy:
  replicaCount: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.3
  wsResources:
    requests:
      memory: 312Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: "-Xms200m -Xmx200m -XX:MaxDirectMemorySize=112m"
  autoPortAssign:
    enablePlainTextWithTLS: true
  service:
    autoPortAssign:
      enabled: true

grafanaDashboards:
  enabled: true

pulsarAdminConsole:
  replicaCount: 1

kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    enabled: true
    adminPassword: e9JYtk83*4#PM8